version: '3'

services:
    nginx:
        image: nginx:alpine
        container_name: webshop_nginx
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
    php:
        image: php:7.4-fpm
        container_name: webshop_php
        build:
            context: docker/php
        ports:
            - 9000:9000
        volumes:
            - ./:/var/www/html
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    mysql:
        image: mysql:5.7
        container_name: webshop_mysql
        ports:
            - 3306:3306
        depends_on:
            - php
        volumes:
            - ./sql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: webshop_db
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
